<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Kontent.Ai.AspNetCore" />
    <PackageReference Include="Kontent.Ai.Delivery" />
    <PackageReference Include="Kontent.Ai.Delivery.SourceGeneration" />
  </ItemGroup>

</Project>
